"""Conversation compaction for long-running chats.

When a chat's history grows past the model's comfortable context window,
sending every prior turn back on every request becomes expensive and starts
to crowd out current task context. The pattern most of the leading harnesses
use (Claude Code, codex, opencode, kimi-cli, …) is:

    keep [first user turn] + [recent N turns]
    summarize the middle into one compact block
    persist that summary so we don't re-summarize on every follow-up

This module is the seam for that. The summary itself is generated by the
same model the user is already chatting with — we deliberately don't add a
new provider dependency or background queue.

Public surface:
    estimate_tokens(messages)              -> int
    should_compact(messages, threshold)    -> bool
    plan_compaction(messages, keep_recent) -> CompactionPlan
    summarize(messages, ...)               -> str  (blocking; calls the LLM)
"""
from __future__ import annotations

import json
from dataclasses import dataclass

import httpx

from . import providers


# ~4 chars per token is the rough rule for English + code mix. Good enough
# to decide when to compact; the model's tokenizer is authoritative when it
# actually matters (the API will reject if we still overshoot).
_CHARS_PER_TOKEN = 4

# Compact when total prompt approaches this many tokens. Most modern models
# allow 200k+ context, but cost and latency climb fast past ~30k input tokens
# on every turn. 30k * 4 = 120k chars.
DEFAULT_COMPACT_THRESHOLD_CHARS = 120_000

# How many recent turns to leave verbatim. Pairs of (user, assistant) — so
# 4 means roughly the last 2 exchanges.
DEFAULT_KEEP_RECENT = 4


def estimate_chars(messages: list[dict]) -> int:
    return sum(len(_msg_text(m)) for m in messages)


def estimate_tokens(messages: list[dict]) -> int:
    return estimate_chars(messages) // _CHARS_PER_TOKEN


def _msg_text(m: dict) -> str:
    c = m.get("content")
    if isinstance(c, str):
        return c
    if isinstance(c, list):
        # Anthropic-shape content blocks
        out: list[str] = []
        for blk in c:
            if isinstance(blk, dict):
                if "text" in blk:
                    out.append(str(blk.get("text") or ""))
                elif blk.get("type") == "tool_result":
                    out.append(str(blk.get("content") or ""))
        return "\n".join(out)
    return ""


def should_compact(
    messages: list[dict],
    threshold_chars: int = DEFAULT_COMPACT_THRESHOLD_CHARS,
    keep_recent: int = DEFAULT_KEEP_RECENT,
) -> bool:
    """Compaction is only worth it when there's something to compact —
    we need at least a few turns past the recent window AND total size has
    crossed the threshold.
    """
    if estimate_chars(messages) < threshold_chars:
        return False
    if len(messages) <= keep_recent + 2:
        return False
    return True


@dataclass
class CompactionPlan:
    keep_head: list[dict]   # messages to keep verbatim from the front
    middle: list[dict]      # messages to summarize
    keep_tail: list[dict]   # messages to keep verbatim from the back
    cursor: int             # index in original list where `keep_tail` starts


def plan_compaction(
    messages: list[dict],
    keep_recent: int = DEFAULT_KEEP_RECENT,
    keep_head: int = 0,
) -> CompactionPlan:
    """Slice the message list into [head | middle | tail].

    By default head is empty: the summarizer prompt tells the model to lead
    with the user's original goals, so the summary itself stands in for
    those early turns. `keep_recent` turns are left verbatim so the model
    has fresh, exact context to act on.
    """
    n = len(messages)
    head_end = min(keep_head, n)
    tail_start = max(head_end, n - keep_recent)
    return CompactionPlan(
        keep_head=list(messages[:head_end]),
        middle=list(messages[head_end:tail_start]),
        keep_tail=list(messages[tail_start:]),
        cursor=tail_start,
    )


SUMMARIZE_PROMPT = (
    "You are summarizing the earlier portion of a conversation between a "
    "user and a desktop AI assistant (zWork). Future turns will rely on "
    "this summary instead of replaying the original messages.\n\n"
    "Preserve, in this order:\n"
    "1. The user's stated goals and any constraints they gave.\n"
    "2. Decisions that have been made and the reasoning when non-obvious.\n"
    "3. Files created or modified and their purpose (give exact paths).\n"
    "4. Tools that were run and what they returned in summary form (don't "
    "quote long output; record outcomes).\n"
    "5. Anything the assistant promised, deferred, or left unfinished.\n\n"
    "Drop pleasantries, drafts that were thrown away, and verbatim tool "
    "output. Output 3 to 8 short paragraphs in plain markdown. No preamble."
)


async def summarize(
    middle_messages: list[dict],
    *,
    creds: providers.Credentials,
    model_id: str,
    shape: str,
    timeout: float = 90.0,
) -> str:
    """Call the same provider/model the user is using to summarize the
    middle of the conversation. Returns the summary text, or a sentinel
    "[compaction failed: …]" string on error so the caller can decide how
    to fall back without raising.
    """
    convo_text = _render_for_summary(middle_messages)
    user_msg = (
        "Conversation snippet to summarize:\n\n<conversation>\n"
        + convo_text
        + "\n</conversation>"
    )
    try:
        if shape == "anthropic":
            return await _summarize_anthropic(creds, model_id, user_msg, timeout)
        return await _summarize_openai(creds, model_id, user_msg, timeout)
    except Exception as e:  # pragma: no cover - best-effort fallback
        return f"[compaction failed: {type(e).__name__}: {e}]"


def _render_for_summary(messages: list[dict]) -> str:
    """Render messages as plain dialogue text for the summarizer prompt."""
    lines: list[str] = []
    for m in messages:
        role = m.get("role", "?")
        text = _msg_text(m).strip()
        if not text:
            continue
        if role == "user":
            lines.append(f"USER: {text}")
        elif role == "assistant":
            lines.append(f"ASSISTANT: {text}")
        elif role == "tool":
            lines.append(f"TOOL_RESULT: {text}")
        else:
            lines.append(f"{role.upper()}: {text}")
    return "\n\n".join(lines)


async def _summarize_anthropic(
    creds: providers.Credentials,
    model_id: str,
    user_msg: str,
    timeout: float,
) -> str:
    url = f"{creds.base_url}/v1/messages"
    headers = {"content-type": "application/json", "anthropic-version": "2023-06-01"}
    if creds.api_key.startswith("sk-ant-"):
        headers["x-api-key"] = creds.api_key
    else:
        headers["authorization"] = f"Bearer {creds.api_key}"
        headers["x-api-key"] = creds.api_key
    body = {
        "model": model_id,
        "max_tokens": 1500,
        "system": SUMMARIZE_PROMPT,
        "messages": [{"role": "user", "content": user_msg}],
    }
    async with httpx.AsyncClient(timeout=httpx.Timeout(timeout, connect=20.0)) as c:
        r = await c.post(url, json=body, headers=headers)
        r.raise_for_status()
        data = r.json()
    blocks = data.get("content") or []
    return "".join(b.get("text", "") for b in blocks if b.get("type") == "text").strip()


async def _summarize_openai(
    creds: providers.Credentials,
    model_id: str,
    user_msg: str,
    timeout: float,
) -> str:
    url = f"{creds.base_url}/chat/completions"
    headers = {"content-type": "application/json"}
    if creds.api_key:
        headers["authorization"] = f"Bearer {creds.api_key}"
    body = {
        "model": model_id,
        "messages": [
            {"role": "system", "content": SUMMARIZE_PROMPT},
            {"role": "user", "content": user_msg},
        ],
        "max_tokens": 1500,
    }
    async with httpx.AsyncClient(timeout=httpx.Timeout(timeout, connect=20.0)) as c:
        r = await c.post(url, json=body, headers=headers)
        r.raise_for_status()
        data = r.json()
    return (
        ((data.get("choices") or [{}])[0].get("message") or {}).get("content") or ""
    ).strip()


def render_summary_message(summary: str) -> dict:
    """Wrap the summary in a synthetic assistant message so it slots into the
    history without changing role semantics. Tagged so the UI/log can show
    that this segment is compacted, not original."""
    body = (
        "[Earlier conversation compacted to fit the context window.]\n\n"
        + (summary or "(no summary produced)").strip()
    )
    return {"role": "assistant", "content": body}


__all__ = [
    "CompactionPlan",
    "DEFAULT_COMPACT_THRESHOLD_CHARS",
    "DEFAULT_KEEP_RECENT",
    "estimate_chars",
    "estimate_tokens",
    "plan_compaction",
    "render_summary_message",
    "should_compact",
    "summarize",
]
